name: Pull Request

on: 
  pull_request:
    types: [ready_for_review]

jobs:

  cancel-previous:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
      env:
        GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: enriikke/gatsby-gh-pages-action@v2
        with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-branch: gh-pages-debug