name: Scheduled Tasks

on:
  schedule:
    # Run at 02:00 (UTC) every Sunday
    - cron:  '0 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages-test