name: Scheduled Tasks

on:
  schedule:
    # Run at 02:00 (UTC) every Sunday
    - cron:  '0 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@fbe063b0cfaa8c16ec4e346cc3c48e9b154cce87  #v2.2.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages-test
          gatsby-args: --no-color